services:
  library:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
      - ./logs:/var/log/postgresql
  backend:
    image: orangefrodo/spring-boot-cds
    ports:
      - "8080:8080"
    depends_on:
      - library
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library:5432/root
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  react:
    image: orangefrodo/react-cds
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - library


