services:
  library:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=root
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "6432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
  backend:
    image: cbdb/backend
    ports:
      - "8080:8080"
    depends_on:
      - library
  frontend:
    image: cbdb/frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
      - library

