spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect